version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install poetry
      - pip install poetry==2.0.1
      # Tell poetry to not create a new virtual environment but use the current one
      - poetry config virtualenvs.create false
    post_install:
      # Install dependencies. Our doc building dependencies are part of the dev group
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install

sphinx:
  configuration: docs/source/conf.py
